# -*- mode: python ; coding: utf-8 -*-
from pathlib import Path

block_cipher = None

# Static assets, templates, and sample data to bundle
datas = [
    ('app/templates', 'app/templates'),
    ('app/static', 'app/static'),
    ('sample_data', 'sample_data'),
]

hiddenimports = [
    'fastapi',
    'starlette',
    'starlette.responses',
    'starlette.routing',
    'starlette.middleware',
    'starlette.staticfiles',
    'starlette.templating',
    'anyio',
    'uvicorn',
    'uvicorn.logging',
    'uvicorn.loops',
    'uvicorn.loops.auto',
    'uvicorn.protocols',
    'uvicorn.protocols.http',
    'uvicorn.protocols.http.auto',
    'uvicorn.protocols.http.h11_impl',
    'uvicorn.protocols.websockets',
    'uvicorn.protocols.websockets.auto',
    'uvicorn.protocols.websockets.websockets_impl',
    'uvicorn.lifespan',
    'uvicorn.lifespan.on',
    'websockets',
    'websockets.legacy',
    'websockets.legacy.server',
    'sqlalchemy',
    'sqlalchemy.dialects.sqlite',
    'sqlalchemy.sql.default_comparator',
    'pydantic',
    'jinja2',
    'email_validator',
    'multipart',
    'psutil',
    'xml.etree.ElementTree',
    'app.parsers.windows_event',
    'app.parsers.web_access',
    'app.parsers.firewall',
    'app.parsers.generic_log',
    'app.parsers.wazuh',
    'app.parsers.suricata',
    'app.parsers.linux_auth',
    'app.security.host_sensor',
    'app.security.remediation',
    'app.security.mitre_mapper',
    'app.security.normalizer',
    'app.security.correlator',
    'app.security.risk_engine',
    'app.security.stream',
    'app.api.routes',
    'app.models.alert',
    'app.models.incident',
]

a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='SOC_Alert_Analyzer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
